### ISSUE TITLE
Alipay Miniprogram & Dingtalk Miniprogram Support?

### ISSUE THREAD

**Issue by weihongyu12** [airbnb/eslint-plugin-miniprogram#7]
There are also two very popular mini programs, but I didn't see them on the documentation. I don't know if they are supported.

- [Alipay Miniprogram](https://mini.open.alipay.com/channel/miniIndex.htm)
- [Dingtalk Miniprogram](https://open-doc.dingtalk.com/microapp/isv/yeun2g)

**Comment by jimexist** [comment]
@weihongyu12 PRs are welcome!
